name: Docker Image CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag thebino/android-build-environment:${{steps.vars.outputs.tag}}

      - name: Download docker container-structure-test tool
        run: curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

      - name: Test the Docker image
        run: /usr/local/bin/container-structure-test test --image thebino/android-build-environment:${{steps.vars.outputs.tag}} --config config.yaml

      - name: Push the tagged Docker image
        run: docker push thebino/android-build-environment:${{steps.vars.outputs.tag}}

      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag thebino/android-build-environment:latest

      - name: Push the latest Docker image
        run: docker push thebino/android-build-environment:latest
